
#DATA
#libraries
library(quantmod)
library(tseries)
library(forecast)
library(vars)
# Download Data
getSymbols("CPIAUCSL", src = "FRED") # Monthly CPI


getSymbols(c("^VIX", "^GSPC"), src = "yahoo", from = "2009-01-01", to = "2024-01-01") 

# Convert Daily to Monthly using last observation of the month
vix_m <- to.monthly(VIX)$VIX.Close
sp500_m <- to.monthly(GSPC)$GSPC.Close
cpi_m <- CPIAUCSL

# Fix Date Alignment: Convert CPI dates to the 'yearmon' format used by Yahoo data
index(cpi_m) <- as.yearmon(index(cpi_m))

# Calculate Log Returns and Inflation Rate
sp500_ret <- diff(log(sp500_m))
inf_rate <- diff(log(cpi_m))

# Merge into a single dataset aligned by date
ts_data <- merge(sp500_ret, inf_rate, vix_m, all = FALSE)
colnames(ts_data) <- c("SP500_Ret", "Inflation", "VIX")

# Create lagged versions for dynamic modeling
ts_data$Inf_Lag <- quantmod::Lag(ts_data$Inflation, k = 1)
ts_data$VIX_Lag <- quantmod::Lag(ts_data$VIX, k = 1)

# Remove NAs generated by diff() and Lag()
ts_data <- na.omit(ts_data)

# SUBSET THE DATA: Restrict exactly to 2010 through 2023
ts_data <- ts_data["2010/2023"]


# PLOT RAW DATA
par(mfrow = c(3, 1), mar = c(2, 4, 5, 1))

#Merge
raw_data <- merge(sp500_m, cpi_m, vix_m, all = FALSE)
colnames(raw_data) <- c("SP500_Raw", "CPI_Raw", "VIX_Raw")

#Remove NAs and subset to the exact 2010-2023 timeframe
raw_data <- na.omit(raw_data)
raw_data <- raw_data["2010/2023"]

#Plot the raw series individually
plot(raw_data$SP500_Raw, 
     main = "Raw S&P 500 Index Price (2010-2023)", 
     col = "black", ylab = "Index Level", xlab = "Time")

plot(raw_data$VIX_Raw, 
     main = "Raw VIX Level (2010-2023)", 
     col = "red", ylab = "VIX Level", xlab = "Time")

plot(raw_data$CPI_Raw, 
     main = "Raw Consumer Price Index (CPI) (2010-2023)", 
     col = "blue", ylab = "CPI Index Number", xlab = "Time")


#PLOT THE TIME SERIES DATA
par(mfrow = c(3, 1), mar = c(2, 4, 5, 1))
plot(ts_data$SP500_Ret, main = "S&P 500 Monthly Log Returns (2010-2023)", 
     col = "black", ylab = "Log Returns", xlab = "Time")

plot(ts_data$VIX, main = "VIX: Market Volatility Index (2010-2023)", 
     col = "red", ylab = "VIX Level", xlab = "Time")

plot(ts_data$Inflation, main = "Monthly Inflation Rate (CPI) (2010-2023)", 
     col = "blue", ylab = "Log Inflation Rate", xlab = "Time")



#AUTOCORRELATIONS & CROSS-CORRELATIONS
acf(ts_data$SP500_Ret, main = "Autocorrelation (ACF): S&P 500 Returns")
acf(ts_data$VIX, main = "Autocorrelation (ACF): VIX")
acf(ts_data$Inflation, main = "Autocorrelation (ACF): Inflation Rate")

ccf(as.numeric(ts_data$VIX), as.numeric(ts_data$SP500_Ret), 
    main = "Cross-Correlation: VIX vs S&P 500 Returns", ylab = "Correlation")

ccf(as.numeric(ts_data$Inflation), as.numeric(ts_data$SP500_Ret), 
    main = "Cross-Correlation: Inflation vs S&P 500 Returns", ylab = "Correlation")



#SPECTRAL ANALYSIS
par(mfrow = c(3, 1))
spec.pgram(ts_data$SP500_Ret, main = "Spectral Analysis: S&P 500 Returns", 
           col = "black", spans = c(3,3))

spec.pgram(ts_data$VIX, main = "Spectral Analysis: VIX", 
           col = "red", spans = c(3,3))

spec.pgram(ts_data$Inflation, main = "Spectral Analysis: Inflation", 
           col = "blue", spans = c(3,3))



#LINEAR DYNAMIC MODELING ARIMA and ARIMAX
mod_arima <- auto.arima(ts_data$SP500_Ret)

mod_arimax_cont <- auto.arima(ts_data$SP500_Ret, 
                              xreg = as.matrix(ts_data[, c("Inflation", "VIX")]))

mod_arimax_lag <- auto.arima(ts_data$SP500_Ret, 
                             xreg = as.matrix(ts_data[, c("Inf_Lag", "VIX_Lag")]))

model_comparison <- data.frame(
  Model = c("ARIMA (No Inputs)", "ARIMAX (Contemporaneous)", "ARIMAX (Lagged)"),
  AIC = c(AIC(mod_arima), AIC(mod_arimax_cont), AIC(mod_arimax_lag)),
  BIC = c(BIC(mod_arima), BIC(mod_arimax_cont), BIC(mod_arimax_lag))
)

cat("\nARIMAX Model Selection Comparison\n")
print(model_comparison[order(model_comparison$AIC), ])

# Diagnostics for ARIMAX
cat("\nResidual Diagnostics ARIMAX Contemporaneous\n")
checkresiduals(mod_arimax_cont)



#VAR MODEL & IMPULSE RESPONSE FUNCTIONS
var_data <- data.frame(
  Inflation = as.numeric(ts_data$Inflation),
  VIX = as.numeric(ts_data$VIX),
  SP500_Ret = as.numeric(ts_data$SP500_Ret)
)

# Select the optimal number of lags (p) for the VAR model
lag_selection <- VARselect(var_data, lag.max = 8, type = "const")
cat("\nVAR Lag Selection (Optimal Lags)\n")
print(lag_selection$selection)

# We will use the lag selected by the AIC criterion
optimal_p <- lag_selection$selection["AIC(n)"]

# 6b. Fit the VAR Model
var_model <- VAR(var_data, p = optimal_p, type = "const")

cat("\nVAR Model Summary\n")
summary(var_model)

#Impulse Response Functions (IRF)
# How does a shock to Inflation affect the VIX?
irf_inf_to_vix <- irf(var_model, impulse = "Inflation", response = "VIX", 
                      n.ahead = 12, boot = TRUE)

# How does a shock to Inflation affect the S&P 500?
irf_inf_to_sp500 <- irf(var_model, impulse = "Inflation", response = "SP500_Ret", 
                        n.ahead = 12, boot = TRUE)

# Plot the IRF
plot(irf_inf_to_vix, main = "Impulse Response: Shock to Inflation -> Response of VIX")
plot(irf_inf_to_sp500, main = "Impulse Response: Shock to Inflation -> Response of S&P 500 Returns")